# Generated by Django 5.0.6 on 2025-04-22 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_car_body_car_color_car_manufacturing_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("odometer", models.PositiveIntegerField()),
                ("liters", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cost_per_liter", models.DecimalField(decimal_places=2, max_digits=4)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("petrol_91", "Petrol 91"),
                            ("petrol_95", "Petrol 95"),
                            ("petrol_98", "Petrol 98"),
                            ("lpg", "LPG"),
                        ],
                        max_length=20,
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=100)),
                ("full_tank", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TireRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.DateField()),
                ("next_change_km", models.PositiveIntegerField()),
                ("alignment_done", models.BooleanField(default=False)),
                ("tire_positions", models.JSONField(default=dict)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["rego"]},
        ),
        migrations.RenameField(
            model_name="maintenance",
            old_name="yearly_cost",
            new_name="total_cost",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="accident_history",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="last_service_date",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="maintenance_actions",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="mechanic_notes",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="monthly_odometer_alert",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="service_alert_km",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="tire_alignment",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="tire_status",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="tires_alert_km",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="tires_change_date",
        ),
        migrations.RemoveField(
            model_name="maintenanceitem",
            name="cost",
        ),
        migrations.AddField(
            model_name="car",
            name="last_service_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="monthly_odometer_check",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="car",
            name="next_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="service_interval_km",
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="car",
            name="total_maintenance_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="documents",
            field=models.FileField(
                blank=True, null=True, upload_to="maintenance_docs/"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="invoice_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="odometer_reading",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="service_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="service_provider",
            field=models.CharField(default="Unknown Provider", max_length=200),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Service"),
                    ("repair", "Repair"),
                    ("inspection", "Inspection"),
                    ("accident", "Accident Repair"),
                    ("other", "Other"),
                ],
                default="regular",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("parts", "Parts"),
                    ("labor", "Labor"),
                    ("consumables", "Consumables"),
                    ("other", "Other"),
                ],
                default="parts",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="maintenanceitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="body",
            field=models.CharField(
                choices=[
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                    ("Ute", "Ute"),
                    ("Van", "Van"),
                    ("Truck", "Truck"),
                    ("EWP", "EWP"),
                    ("trailer", "trailer"),
                    ("Other", "Other"),
                ],
                default="Sedan",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["rego"], name="tracking_ca_rego_a71ceb_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["state"], name="tracking_ca_state_871d7d_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["assigned_user"], name="tracking_ca_assigne_3f6ed5_idx"
            ),
        ),
        migrations.AddField(
            model_name="fuelrecord",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_records",
                to="tracking.car",
            ),
        ),
        migrations.AddField(
            model_name="tirerecord",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tire_records",
                to="tracking.car",
            ),
        ),
    ]
