# Generated by Django 5.0.6 on 2025-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_fuelrecord_tirerecord_alter_car_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='maintenance_sticker_date',
        ),
        migrations.AddField(
            model_name='car',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Current odometer reading in kilometers'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_odometer',
            field=models.PositiveIntegerField(default=10000, help_text='Odometer reading when next service is due'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='Quantity can be decimal (e.g., 1.5 liters)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('NSW-Wireless', 'NSW-Wireless'), ('NSW-Special', 'NSW-Special'), ('VIC', 'VIC'), ('WA', 'WA'), ('SA', 'SA'), ('QLD', 'QLD'), ('TZ', 'TZ')], max_length=15, null=True),
        ),
    ]
