# Generated by Django 5.0.6 on 2025-10-29 23:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_update_car_odometer_and_maintenance_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateField(default=django.utils.timezone.now)),
                ('accident_excess', models.DecimalField(decimal_places=2, default=0.0, help_text='Excess amount paid', max_digits=10)),
                ('via_insurance', models.BooleanField(default=True, help_text='Was this processed through insurance?')),
                ('insurance_company', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the accident')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('claim_number', models.CharField(blank=True, default='', max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='tracking.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accident_date'],
            },
        ),
    ]
