# Generated by Django 5.0.6 on 2026-04-07 02:37

from collections import defaultdict

from django.db import migrations, models
from django.db.models import Q


def dedupe_and_normalize_invoice_numbers(apps, schema_editor):
    """
    Merge duplicate maintenance rows that share the same normalized invoice number
    (keep newest by service_date, then highest pk). Normalize stored invoice_number
    to strip + uppercase for consistency with import code.
    """
    Maintenance = apps.get_model("tracking", "Maintenance")

    def norm(s):
        if not s:
            return ""
        return str(s).strip().upper()

    groups = defaultdict(list)
    for m in Maintenance.objects.exclude(invoice_number="").iterator():
        key = norm(m.invoice_number)
        if not key:
            continue
        groups[key].append(m.pk)

    for key, pks in groups.items():
        if len(pks) <= 1:
            continue
        rows = list(Maintenance.objects.filter(pk__in=pks).order_by("-service_date", "-pk"))
        keeper = rows[0]
        for loser in rows[1:]:
            loser.delete()
        if keeper.invoice_number != key:
            keeper.invoice_number = key
            keeper.save(update_fields=["invoice_number"])

    for m in Maintenance.objects.exclude(invoice_number="").iterator():
        n = norm(m.invoice_number)
        if m.invoice_number != n:
            m.invoice_number = n
            m.save(update_fields=["invoice_number"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_accident"),
    ]

    operations = [
        migrations.RunPython(dedupe_and_normalize_invoice_numbers, noop_reverse),
        migrations.AddConstraint(
            model_name="maintenance",
            constraint=models.UniqueConstraint(
                condition=~Q(invoice_number=""),
                fields=("invoice_number",),
                name="maintenance_invoice_number_nonempty_unique",
            ),
        ),
    ]
