# Generated by Django 5.2.16 on 2026-08-12 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_car_qr_tokens(apps, schema_editor):
    Car = apps.get_model('tracking', 'Car')
    for car in Car.objects.filter(qr_token__isnull=True).iterator():
        car.qr_token = uuid.uuid4()
        car.save(update_fields=['qr_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_accident_excess_nonnegative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='final_odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='final_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='final_payment_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='car',
            name='final_payment_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='qr_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_car_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='car',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='retired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='retirement_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_retirement_docs/'),
        ),
        migrations.AddField(
            model_name='car',
            name='retirement_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('in_service', 'In service'), ('sold', 'Sold'), ('written_off', 'Written off')], db_index=True, default='in_service', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleRetirementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('rego_refund', 'Apply for registration refund'), ('ctp_refund', 'Apply for CTP refund'), ('nrma_remove', 'Remove from NRMA roadside assistance'), ('insurance_remove', 'Remove from insurance policy'), ('fuel_card', 'Cancel or recover fuel card'), ('toll_tag', 'Remove toll account or tag'), ('tracking', 'Remove GPS or tracking equipment'), ('equipment', 'Recover company tools and equipment'), ('documents', 'Upload retirement documents'), ('payment', 'Confirm final payment received')], max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_tasks', to='tracking.car')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_vehicle_retirement_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('car', 'task_type'), name='vehicle_retirement_task_unique')],
            },
        ),
    ]
