# Generated by Django 5.2.16 on 2026-08-12 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_transfer_task_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodylocation',
            options={'ordering': ['state', 'location_type', 'name']},
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office'), ('warehouse', 'Warehouse')], default='warehouse', max_length=20),
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_company_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodylocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
