# Generated by Django 5.2.16 on 2026-08-12 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_company_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vehicle_service', 'Vehicle service'), ('special_maintenance', 'Special maintenance'), ('calibration', 'Tool calibration'), ('written_off', 'Vehicle written off'), ('retirement', 'Retirement checklist'), ('controlled_transfer', 'Controlled-device transfers'), ('odometer', 'Odometer reminders')], max_length=50)),
                ('related_object', models.CharField(blank=True, default='', max_length=150)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('deduplication_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('responsibility', models.CharField(choices=[('fleet_manager', 'Fleet Manager'), ('state_manager', 'State Manager'), ('admin_alerts', 'Admin Alerts')], max_length=30)),
                ('state', models.CharField(blank=True, choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('WA', 'WA'), ('SA', 'SA'), ('QLD', 'QLD'), ('TZ', 'TZ')], max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary State Manager used for controlled-device routing.')),
                ('categories', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_contacts', to=settings.AUTH_USER_MODEL)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_contacts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_alert_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['responsibility', 'state', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True), ('responsibility', 'state_manager')), fields=('state',), name='one_primary_state_alert_contact')],
            },
        ),
    ]
