# Generated by Django 5.2.16 on 2026-08-12 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_email_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='calibration_required',
            field=models.BooleanField(default=False, help_text='This device must always have a next calibration due date.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs repair'), ('out_of_service', 'Out of service')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_controlled',
            field=models.BooleanField(db_index=True, default=False, help_text='Rare, shared, important, or high-value device requiring enhanced custody controls.'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
