# Generated by Django 5.2.16 on 2026-08-12 07:57

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def seed_tool_catalogue(apps, schema_editor):
    Tool = apps.get_model('tracking', 'Tool')
    ToolCatalogueItem = apps.get_model('tracking', 'ToolCatalogueItem')
    names = {}
    for value, label in Tool._meta.get_field('tool_name').flatchoices:
        clean_name = ' '.join(str(value).split())
        if clean_name:
            names.setdefault(clean_name.casefold(), clean_name)
    for value in Tool.objects.values_list('tool_name', flat=True).distinct():
        clean_name = ' '.join((value or '').split())
        if clean_name:
            names.setdefault(clean_name.casefold(), clean_name)

    controlled_terms = (
        'pim', 'otdr', 'splicer', 'power meter', 'light source',
        'traffic identifier', 'microscope', 'gas tester',
    )
    calibration_terms = (
        'pim', 'otdr', 'power meter', 'light source', 'gas tester',
    )
    ToolCatalogueItem.objects.bulk_create([
        ToolCatalogueItem(
            name=name,
            suggested_controlled=any(term in name.casefold() for term in controlled_terms),
            suggested_calibration_required=any(
                term in name.casefold() for term in calibration_terms
            ),
        )
        for name in sorted(names.values(), key=str.casefold)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_controlled_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('suggested_controlled', models.BooleanField(default=False, help_text='Suggest controlled-device handling when this type is selected.')),
                ('suggested_calibration_required', models.BooleanField(default=False, help_text='Suggest calibration tracking when this type is selected.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_catalogue_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tool_catalogue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tool_catalogue_name_ci')],
            },
        ),
        migrations.RunPython(seed_tool_catalogue, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
