# Generated by Django 5.2.17 on 2026-08-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_searchable_tool_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='odometer_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_record', to='tracking.odometerreading'),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='fuel_receipts/'),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_fuel_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='evidence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='odometer_evidence/'),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='review_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Needs review'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=12),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_odometer_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr', 'Vehicle QR')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_odometer_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='suspicious_reason',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.CreateModel(
            name='SpecialMaintenanceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('advance_notice_days', models.PositiveIntegerField(default=30)),
                ('advance_notice_km', models.PositiveIntegerField(default=1000)),
                ('recurrence_days', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_km', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('completion_document', models.FileField(blank=True, null=True, upload_to='special_maintenance_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_maintenance_requirements', to='tracking.car')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_special_maintenance_requirements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_maintenance_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['active', 'due_date', 'due_odometer', 'car__rego'],
            },
        ),
    ]
