# Generated by Django 5.2.17 on 2026-08-22 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_vehicle_monitoring_special_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='odometer_tracking_started_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
